from __future__ import annotations


def backtest_page() -> str:
    return HISTORICAL_BACKTEST_HTML


HISTORICAL_BACKTEST_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>历史回测 - AI量化交易平台</title>
  <style>
    :root{font-family:"Microsoft YaHei","PingFang SC",Arial,sans-serif;--navy:#111827;--page:#f6f7f9;--panel:#fff;--border:#dfe3e8;--line:#e8ebef;--muted:#667085;--blue:#2563eb;--green:#059669;--red:#dc2626;--amber:#d97706}
    *{box-sizing:border-box}html,body{margin:0;height:100%;background:var(--page);color:#171717}body{font-size:12px;overflow:hidden}
    .header{height:52px;padding:7px 18px;background:var(--navy);color:#fff;display:flex;align-items:center;justify-content:space-between}.brand h1{font-size:19px;margin:0}.brand p{font-size:11px;color:#cbd5e1;margin:3px 0 0}.status{font-size:11px;color:#94a3b8;white-space:nowrap}
    .nav{height:38px;background:#fff;border-bottom:1px solid var(--border);display:flex;padding:0 16px;gap:6px}.nav a{display:flex;align-items:center;padding:0 13px;text-decoration:none;color:#64748b;font-weight:700;border-bottom:2px solid transparent}.nav a.active{color:var(--blue);border-color:var(--blue)}
    .metrics{height:76px;padding:8px 12px;display:grid;grid-template-columns:repeat(8,minmax(88px,1fr)) minmax(145px,1.35fr);gap:8px;overflow-x:auto}.metric,.panel{background:#fff;border:1px solid var(--border);border-radius:7px;box-shadow:0 1px 2px rgba(15,23,42,.04)}.metric{min-width:0;padding:8px 9px}.metric label{display:block;color:var(--muted);font-size:10px;white-space:nowrap}.metric strong{display:block;margin-top:7px;font-size:14px;white-space:nowrap}.positive{color:var(--green)!important}.negative{color:var(--red)!important}
    .workspace{height:calc(100vh - 166px);padding:0 12px 10px;display:grid;grid-template-columns:460px minmax(0,1fr);gap:8px}.left{padding:8px 10px;display:flex;flex-direction:column;min-height:0;overflow:hidden}.left h2,.right h2{font-size:14px;margin:0 0 8px}.date-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.field label{display:block;color:var(--muted);font-size:10px;margin-bottom:4px}input,button{font:inherit}input{width:100%;height:31px;border:1px solid #d6dbe2;border-radius:5px;padding:0 8px}button{height:34px;border:0;border-radius:5px;font-weight:700;cursor:pointer}.actions{display:grid;grid-template-columns:1.4fr 1fr;gap:7px;margin-top:8px}.primary{background:var(--blue);color:#fff}.secondary{background:#e9edf2;color:#344054}button:disabled{opacity:.5;cursor:not-allowed}.error{color:var(--red)!important}
    .analysis{margin-top:10px;padding-top:8px;border-top:1px solid var(--line);min-height:90px;overflow-y:scroll;scrollbar-gutter:stable;flex:1 1 auto}.analysis h3,.curve h3{font-size:12px;margin:0 0 5px}.analysis h3{position:sticky;top:0;z-index:1;padding-bottom:4px;background:#fff}.analysis-lines{color:#475467;line-height:1.5}.analysis-line{display:block;padding:6px 4px;border-bottom:1px solid var(--line);overflow-wrap:anywhere}.analysis-line:last-child{border-bottom:0}.analysis-line strong{color:#111827}.analysis-line.loss-line strong{color:var(--red)}
    .curve{margin-top:10px;padding-top:8px;border-top:1px solid var(--line);height:clamp(220px,31vh,340px);min-height:220px;flex:0 0 clamp(220px,31vh,340px);overflow:hidden;display:flex;flex-direction:column}.curve-head{display:flex;justify-content:space-between;color:var(--muted)}#equityChart{flex:1;min-height:0}.chart-empty{height:100%;display:grid;place-items:center;color:#98a2b3}.chart-svg{width:100%;height:100%;display:block}.axis{stroke:#e5e7eb;stroke-width:1}.day-tick{fill:#667085;font-size:8px;text-anchor:middle}
    .right{display:grid;grid-template-rows:30% 38% minmax(0,1fr);gap:8px;min-height:0}.right>.panel{min-height:0;padding:9px;overflow:hidden;display:flex;flex-direction:column}.section-head{display:flex;align-items:center;justify-content:space-between}.section-head small{color:var(--muted)}.table-wrap{min-height:0;overflow:auto;flex:1}table{width:100%;border-collapse:collapse;font-size:10px}th{position:sticky;top:0;z-index:1;background:#f8fafc;color:#596579;text-align:left;padding:6px;white-space:nowrap}td{padding:6px;border-top:1px solid var(--line);white-space:nowrap;vertical-align:top}.reason{white-space:normal;min-width:260px;line-height:1.35}.empty td{text-align:center;color:#98a2b3;padding:24px}
    .badge{display:inline-block;padding:2px 6px;border-radius:12px;background:#eef2ff;color:#4338ca}.failure{color:var(--red);white-space:normal;min-width:180px}
    @media(max-width:1100px){body{overflow:auto}.workspace{height:auto;grid-template-columns:1fr}.left{height:720px;min-height:720px}.right{height:900px}}
    @media(max-width:620px){.status{display:none}.workspace{padding:0 7px 8px}.date-grid{grid-template-columns:1fr}.right{height:1050px}.reason{min-width:200px}}
  </style>
</head>
<body>
  <header class="header"><div class="brand"><h1>AI 量化交易平台</h1><p>历史行情只驱动本地模拟账户，不会产生真实订单。</p></div><div class="status" id="globalStatus">读取系统状态中...</div></header>
  <nav class="nav"><a href="/">实时交易</a><a class="active" href="/backtest">历史回测</a></nav>
  <section class="metrics" id="metrics"></section>
  <main class="workspace">
    <aside class="panel left">
      <h2>历史回测</h2>
      <div class="date-grid"><div class="field"><label for="startDate">开始回测时间</label><input id="startDate" type="date"></div><div class="field"><label for="endDate">结束回测时间</label><input id="endDate" type="date"></div></div>
      <div class="actions"><button class="primary" id="runButton" onclick="runBacktest()">启动回测</button><button class="secondary" id="cancelButton" onclick="cancelBacktest()" disabled>取消回测</button></div>
      <section class="analysis"><h3>分析总结</h3><div class="analysis-lines" id="failureSummary"><div class="analysis-line">暂无分析结果</div></div></section>
      <section class="curve"><div class="curve-head"><h3>总收益曲线</h3><span id="curvePeriod">开始时间 - 结束时间</span></div><div id="equityChart"><div class="chart-empty">暂无回测数据</div></div></section>
    </aside>
    <section class="right">
      <article class="panel"><div class="section-head"><h2>持仓</h2><small>结束时间仍持仓则按市值计入总权益</small></div><div class="table-wrap"><table><thead><tr><th>币种</th><th>方向</th><th>杠杆</th><th>入场</th><th>现价</th><th>数量</th><th>保证金</th><th>浮盈亏</th><th>收益率</th><th>止损</th><th>止盈</th><th>入场原因</th></tr></thead><tbody id="positions"><tr class="empty"><td colspan="12">暂无数据</td></tr></tbody></table></div></article>
      <article class="panel"><div class="section-head"><h2>策略信号</h2><small id="universeLabel">固定当前Top50，非历史Top50</small></div><div class="table-wrap"><table><thead><tr><th>币种</th><th>动作</th><th>状态</th><th>风险</th><th>主周期</th><th>分数</th><th>入场位置</th><th>原因</th><th>否决</th></tr></thead><tbody id="signals"><tr class="empty"><td colspan="9">暂无数据</td></tr></tbody></table></div></article>
      <article class="panel"><div class="section-head"><h2>成交记录与失败归因</h2><small id="skippedLabel"></small></div><div class="table-wrap"><table><thead><tr><th>币种</th><th>方向</th><th>杠杆</th><th>开仓价</th><th>平仓价</th><th>收益</th><th>实际R</th><th>开仓时间</th><th>平仓时间</th><th>出场原因</th><th>失败根因</th><th>证据</th></tr></thead><tbody id="trades"><tr class="empty"><td colspan="12">暂无数据</td></tr></tbody></table></div></article>
    </section>
  </main>
  <script>
    const apiToken=localStorage.getItem('AI_TRADING_API_TOKEN');let jobId=null,pollTimer=null,result=null;
    async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(apiToken)headers['X-API-Token']=apiToken;const response=await fetch(path,{...options,headers});if(!response.ok){let detail=`HTTP ${response.status}`;try{detail=(await response.json()).detail||detail}catch(_){}throw new Error(detail)}return response.json()}
    const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
    const pct=value=>`${(Number(value||0)*100).toFixed(2)}%`;const money=value=>`${Number(value||0)>=0?'+':''}${Number(value||0).toFixed(2)} U`;const cls=value=>Number(value||0)>=0?'positive':'negative';const price=value=>Number(value||0).toPrecision(6);
    function initDates(){const end=new Date(),start=new Date(end);start.setDate(start.getDate()-14);document.getElementById('endDate').value=end.toISOString().slice(0,10);document.getElementById('startDate').value=start.toISOString().slice(0,10)}
    function metric(label,value='--',className=''){return `<article class="metric"><label>${label}</label><strong class="${className}">${value}</strong></article>`}
    function renderEmptyMetrics(){document.getElementById('metrics').innerHTML=['资金','可用','占用保证金','已实现','未实现','手续费','胜率','最大回撤','总收益'].map(label=>metric(label)).join('')}
    async function runBacktest(){clearInterval(pollTimer);result=null;document.getElementById('runButton').disabled=true;document.getElementById('cancelButton').disabled=false;const summary=document.getElementById('failureSummary');summary.classList.remove('error');summary.innerHTML='<div class="analysis-line">回测运行中，完成后显示分析总结。</div>';try{const payload={start_date:document.getElementById('startDate').value,end_date:document.getElementById('endDate').value};const job=await api('/api/backtests/jobs',{method:'POST',body:JSON.stringify(payload)});jobId=job.id;updateJob(job);pollTimer=setInterval(pollJob,700)}catch(error){showError(error.message);finishControls()}}
    async function pollJob(){if(!jobId)return;try{const job=await api(`/api/backtests/jobs/${jobId}?include_result=true`);updateJob(job);if(['COMPLETED','FAILED','CANCELLED'].includes(job.status)){clearInterval(pollTimer);pollTimer=null;finishControls();if(job.status==='COMPLETED'){result=job.result;renderResult()}else if(job.error)showError(job.error)}}catch(error){showError(error.message);clearInterval(pollTimer);finishControls()}}
    async function cancelBacktest(){if(jobId)await api(`/api/backtests/jobs/${jobId}/cancel`,{method:'POST'})}
    function finishControls(){const button=document.getElementById('runButton');button.disabled=false;button.textContent='启动回测';document.getElementById('cancelButton').disabled=true}
    function updateJob(job){document.getElementById('runButton').textContent=`回测中 ${job.progress||0}%`}
    function showError(message){const host=document.getElementById('failureSummary');host.innerHTML=`<div class="analysis-line">${esc(message)}</div>`;host.classList.add('error')}
    function renderResult(){const s=result.summary||{},a=result.account||{},analysis=result.analysis||{};document.getElementById('metrics').innerHTML=[metric('资金',`${Number(a.equity||0).toFixed(2)} U`),metric('可用',`${Number(a.available_balance||0).toFixed(2)} U`),metric('占用保证金',`${Number(a.used_margin||0).toFixed(2)} U`),metric('已实现',money(a.realized_pnl),cls(a.realized_pnl)),metric('未实现',money(a.unrealized_pnl),cls(a.unrealized_pnl)),metric('手续费',money(-Number(a.fees_paid||0)),'negative'),metric('胜率',pct(s.win_rate),cls(s.win_rate)),metric('最大回撤',pct(s.max_drawdown),Number(s.max_drawdown||0)>0?'negative':''),metric('总收益',`${money(s.total_pnl)} / ${pct(s.total_return)}`,cls(s.total_pnl))].join('');renderAnalysis(analysis);document.getElementById('universeLabel').textContent=`固定当前Top50 · 实际可用${(result.universe||[]).length}个`;document.getElementById('skippedLabel').textContent=(result.skipped_symbols||[]).length?`跳过${result.skipped_symbols.length}个数据不完整币种`:'';const p=result.period||{};document.getElementById('curvePeriod').textContent=`${String(p.start||'').slice(0,10)} - ${String(p.end||'').slice(0,10)}`;renderCurve(result.equity_curve||[],p);renderPositions(a.positions||[]);renderSignals(a.latest_signals||{});renderTrades(analysis.lifecycles||[])}
    function renderAnalysis(analysis){const host=document.getElementById('failureSummary'),rows=analysis.symbol_summaries||[];host.classList.remove('error');if(!rows.length){host.innerHTML=`<div class="analysis-line">${esc(analysis.failure_summary||'本区间暂无完成交易')}</div>`;return}host.innerHTML=rows.map(row=>{const symbol=String(row.symbol||'').replace(/USDT$/,'/USDT'),causes=(row.causes||[]).map(item=>`${item.cause}${item.count}笔`).join('、'),evidence=(row.evidence||[]).join('；'),parts=[`完成${row.trades||0}笔，胜${row.wins||0}负${row.losses||0}`,`净收益${money(row.pnl)}`];parts.push(causes?`失败根因：${causes}`:'未发现亏损交易');if(evidence)parts.push(`证据：${evidence}`);return `<div class="analysis-line ${Number(row.pnl||0)<0?'loss-line':''}"><strong>${esc(symbol)}</strong>：${esc(parts.join('；'))}</div>`}).join('')}
    function renderPositions(rows){document.getElementById('positions').innerHTML=rows.length?rows.map(row=>`<tr><td>${esc(row.symbol)}</td><td class="${row.side==='LONG'?'positive':'negative'}">${row.side}</td><td>${row.leverage}x</td><td>${price(row.entry_price)}</td><td>${price(row.mark_price)}</td><td>${Number(row.quantity||0).toFixed(4)}</td><td>${Number(row.margin_usdt||0).toFixed(2)}</td><td class="${cls(row.unrealized_pnl)}">${money(row.unrealized_pnl)}</td><td class="${cls(row.unrealized_pnl_pct_on_margin)}">${pct(row.unrealized_pnl_pct_on_margin)}</td><td>${price(row.stop_price)}</td><td>${price(row.take_profit_2)}</td><td class="reason">${esc(row.entry_reason||row.reason)}</td></tr>`).join(''):'<tr class="empty"><td colspan="12">结束时间没有未平仓仓位</td></tr>'}
    function renderSignals(mapping){const rows=Object.entries(mapping).map(([symbol,row])=>({symbol,...row}));rows.sort((a,b)=>Number(b.score||0)-Number(a.score||0));document.getElementById('signals').innerHTML=rows.length?rows.map(row=>`<tr><td>${esc(row.symbol)}</td><td><span class="badge">${esc(row.action||row.candidate_action||'观察')}</span></td><td>${esc(row.trend_state||row.regime||'-')}</td><td>${esc(row.risk_state||'-')}</td><td>${esc(row.signal_timeframe||'1h')}</td><td>${row.score||0}</td><td>${esc(row.entry_position||row.entry_timing||'-')}</td><td class="reason">${esc((row.reasons||[]).join('；'))}</td><td class="reason negative">${esc((row.vetoes||[]).join('；')||row.auto_entry_block_reason||'')}</td></tr>`).join(''):'<tr class="empty"><td colspan="9">本区间没有形成信号</td></tr>'}
    function renderTrades(rows){document.getElementById('trades').innerHTML=rows.length?rows.map(row=>`<tr><td>${esc(row.symbol)}</td><td class="${row.side==='LONG'?'positive':'negative'}">${row.side}</td><td>${row.leverage}x</td><td>${price(row.entry_price)}</td><td>${price(row.exit_price)}</td><td class="${cls(row.pnl)}">${money(row.pnl)}</td><td class="${cls(row.realized_r)}">${Number(row.realized_r||0).toFixed(2)}R</td><td>${new Date(row.opened_at).toLocaleString()}</td><td>${new Date(row.closed_at).toLocaleString()}</td><td class="reason">${esc(row.exit_reason)}</td><td class="failure">${esc(row.failure_cause||'-')}</td><td class="reason">${esc(row.failure_evidence||'')}</td></tr>`).join(''):'<tr class="empty"><td colspan="12">没有完成交易；请查看信号否决原因</td></tr>'}
    function renderCurve(points,period={}){const host=document.getElementById('equityChart');if(points.length<2){host.innerHTML='<div class="chart-empty">暂无可绘制数据</div>';return}const w=460,h=170,l=42,r=7,t=8,b=30,values=points.map(p=>Number(p.equity||0));let min=Math.min(...values),max=Math.max(...values);if(max===min){max+=1;min-=1}const x=i=>l+i*(w-l-r)/Math.max(points.length-1,1),y=v=>t+(max-v)*(h-t-b)/(max-min),line=values.map((v,i)=>`${x(i)},${y(v)}`).join(' '),grid=[0,.5,1].map(q=>{const v=max-(max-min)*q,yy=y(v);return `<line class="axis" x1="${l}" x2="${w-r}" y1="${yy}" y2="${yy}"/><text x="2" y="${yy+3}" font-size="9" fill="#667085">${v.toFixed(1)}</text>`}).join(''),start=String(period.start||points[0].timestamp).slice(0,10),end=String(period.end||points.at(-1).timestamp).slice(0,10),parts=start.split('-').map(Number),endParts=end.split('-').map(Number),startDay=Date.UTC(parts[0],parts[1]-1,parts[2]),endDay=Date.UTC(endParts[0],endParts[1]-1,endParts[2]),dayCount=Math.max(Math.round((endDay-startDay)/86400000)+1,1),ticks=Array.from({length:dayCount},(_,i)=>{const day=new Date(startDay+i*86400000),xx=l+i*(w-l-r)/Math.max(dayCount-1,1);return `<line class="axis" x1="${xx}" x2="${xx}" y1="${h-b}" y2="${h-b+4}"/><text class="day-tick" x="${xx}" y="${h-7}">${day.getUTCDate()}</text>`}).join('');host.innerHTML=`<svg class="chart-svg" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none">${grid}${ticks}<polyline points="${line}" fill="none" stroke="#059669" stroke-width="2" vector-effect="non-scaling-stroke"/></svg>`}
    async function refreshHeader(){try{const h=await api('/api/health');document.getElementById('globalStatus').textContent=`行情与持仓管理${h.running?'运行中':'未运行'} | 新开仓${h.auto_trade?'允许':'禁止'} | ${new Date().toLocaleString()}`}catch(_){}}
    initDates();renderEmptyMetrics();refreshHeader();setInterval(refreshHeader,15000);
  </script>
</body>
</html>"""
